version: "3.3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "bun ./src/index.ts"
    network_mode: "host"
    restart: always
    volumes:
      - "./:/app"
    environment:
      CC_WWWROOT_PORT: "60050"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:60050"]
      interval: 30s
      timeout: 10s
      retries: 3
